//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiFi.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HiFiDBEntities : DbContext
    {
        public HiFiDBEntities()
            : base("name=HiFiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compPictureTBL> compPictureTBL { get; set; }
        public virtual DbSet<logTBL> logTBL { get; set; }
        public virtual DbSet<memberTBL> memberTBL { get; set; }
        public virtual DbSet<setupComponentTBL> setupComponentTBL { get; set; }
        public virtual DbSet<setupPictureTBL> setupPictureTBL { get; set; }
        public virtual DbSet<setupTBL> setupTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<systemCategoryTBL> systemCategoryTBL { get; set; }
        public virtual DbSet<applicationTBL> applicationTBL { get; set; }
    }
}
