//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiFi.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupComponentTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setupComponentTBL()
        {
            this.compPictureTBL = new HashSet<compPictureTBL>();
        }
    
        public int compId { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> setupId { get; set; }
        public string compDetail { get; set; }
        public Nullable<int> ctgId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compPictureTBL> compPictureTBL { get; set; }
        public virtual memberTBL memberTBL { get; set; }
        public virtual systemCategoryTBL systemCategoryTBL { get; set; }
        public virtual setupTBL setupTBL { get; set; }
    }
}
