//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiFi.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setupTBL()
        {
            this.setupComponentTBL = new HashSet<setupComponentTBL>();
            this.setupPictureTBL = new HashSet<setupPictureTBL>();
        }
    
        public int setupId { get; set; }
        public Nullable<int> memberId { get; set; }
        public string setupName { get; set; }
        public Nullable<bool> setupActive { get; set; }
        public string setupDetail { get; set; }
    
        public virtual memberTBL memberTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setupComponentTBL> setupComponentTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setupPictureTBL> setupPictureTBL { get; set; }
    }
}
