//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiFi.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemCategoryTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public systemCategoryTBL()
        {
            this.setupComponentTBL = new HashSet<setupComponentTBL>();
        }
    
        public int ctgId { get; set; }
        public string ctgName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setupComponentTBL> setupComponentTBL { get; set; }
    }
}
